services:
  stock_ai_agent:
    init: true
    build:
      dockerfile: Dockerfile
    image: stock-ai-agent:latest
    container_name: stock_ai_agent
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure